## Feign general configurations
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

## Sonar
sonar:
  project:
    projectOwner: spring-projects
    projectName: spring-boot
    token: df58871d24a25b130af464c6a1e982560f96d9ec
    autoConnectEnabled: true

# sonar feign client props
sonarClient:
  ribbon:
    listOfServers: http://localhost:9000

# disable eureka in ribbon
ribbon:
  eureka:
    enabled: false

## MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eylmz?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: Emre.1991
    driver-class-name: org.gjt.mm.mysql.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: true