## Feign general configurations
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

## Sonar
sonar:
  project:
    projectOwner: ReactiveX
    projectName: RxJava
    projectUuid: AXZipb1ICl93wm5yKTEQ
    token: df58871d24a25b130af464c6a1e982560f96d9ec
    autoConnectEnabled: true

# sonar feign client props
sonarClient:
  ribbon:
    listOfServers: http://localhost:9000

# disable eureka in ribbon
ribbon:
  eureka:
    enabled: false

## MySQL
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:postgresql://localhost:5432/sonar
    username: emreyilmaz
    password: Emre.1991
